### ISSUE TITLE
How may I share a secret between two steps?

### ISSUE THREAD

**Issue by jeanchilger** [cloudposse/github-action-secret-outputs#29]
I am using a single job. A `step1` will generate a _secret_ and a `step2` will consume this _secret_. I came across this action and thought in using it to accomplish that. Here is an exmaple of what I have tried:

```
      - name: Encodes JWT
        uses: cloudposse/github-action-secret-outputs@main
        id: store-jwt
        with:
          secret: D955E283528E128AFDBE10E439168691754EB101
          op: encode
          in: ${{ env.MY_JWT }}
      - name: Decodes JWT
        uses: cloudposse/github-action-secret-outputs@main
        id: get-jwt
        with:
          secret: D955E283528E128AFDBE10E439168691754EB101
          op: decode
          in: ${{ steps.store-jwt.outputs.out }}
      
      ...
      
      - name: Consume secret through API
        uses: fake/do-api-stuff
        with:
          token: steps.get-jwt.outputs.out
```

Getting an error though, so cannot validate if this works:
![image](https://github.com/user-attachments/assets/966ce713-e569-40b0-a445-355f67a6685a)

Any help is welcome. Thanks!
